"""add assignment association table

Revision ID: 1dfacd8dd924
Revises: 91779401994c
Create Date: 2024-04-07 02:34:41.730817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dfacd8dd924'
down_revision = '91779401994c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_assignments_project_id_projects'), 'assignments', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_assignments_project_id_projects'), 'assignments', type_='foreignkey')
    op.drop_column('assignments', 'project_id')
    # ### end Alembic commands ###
